// JsFromRoutes CacheKey b13e91bd2580f328c4dfa7658552408b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/pings'),
}
